# Generated by Django 5.1.5 on 2025-02-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='category',
            field=models.CharField(choices=[('mobility', 'Mobility Issues'), ('emergency', 'Emergency'), ('behaviour', 'Behaviour'), ('brain_spinal', 'Brain & Spinal'), ('breathing', 'Breathing'), ('breeds', 'Breeds'), ('ears', 'Ears'), ('eyes', 'Eyes'), ('fleas', 'Fleas, Ticks & Worms'), ('hazards', 'Hazards & Poisons'), ('joints', 'Joints & Mobility'), ('mouth', 'Mouth & Teeth'), ('nails_pads', 'Nails & Pads'), ('nose', 'Nose'), ('older_pet', 'Older Pet'), ('other', 'Other'), ('tummy', 'Poorly Tummy'), ('pregnancy', 'Pregnancy & Genitals'), ('seasonal', 'Seasonal'), ('skin_coat', 'Skin & Coat'), ('tail', 'Tail'), ('urinary', 'Urinary'), ('wounds_trauma', 'Wounds & Trauma')], max_length=50),
        ),
    ]
