# Generated by Django 5.1.5 on 2025-01-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('mobility', 'Mobility Issues'), ('fleas', 'Fleas, Ticks & Worms'), ('joints', 'Joints & Mobility'), ('mouth', 'Mouth & Teeth'), ('tummy', 'Poorly Tummy')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, upload_to='symptom_icons/')),
            ],
        ),
    ]
